#! /bin/sh

# background
feh --bg-fill ~/.config/bspwm/wallpaper.jpg & # wallpaper
pgrep -x sxhkd > /dev/null || sxhkd & # hotkey daemon
pgrep -x picom > /dev/null || picom --experimental-backends & # x composer
pgrep -x fcitx > /dev/null || fcitx & # imput method framework
pgrep -x dunst > /dev/null || dunst & # notifications
$HOME/.config/polybar/launch.sh # polybar status bar

xsetroot -cursor_name left_ptr # change cursor
if [ -f "$HOME/.config/bspwm/startup_apps.sh" ]; then
	~/.config/bspwm/startup_apps.sh &
fi


# constants
bspc config top_padding        0
bspc config bottom_padding     0
bspc config left_padding       0
bspc config right_padding      0
bspc config border_width       3
bspc config window_gap         8

# monocle
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config single_monocle true

# border colors
bspc config urgent_border_color   "#f1fa8c"
bspc config focused_border_color  "#bd93f9"
bspc config active_border_color   "#6272a4"
bspc config normal_border_color   "#44475a"

# presel
bspc config presel_feedback_color "#6272a4"

# opacity
bspc config normal_frame_opacity 1
bspc config focused_frame_opacity 1

# multihead behavior
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

# focusing behavior
bspc config focus_follows_pointer false
bspc config history_aware_focus true
bspc config focus_by_distance true

# misc
bspc config split_ratio 0.50
bspc confic automatic_scheme longest_side
bspc config auto_alternate true
bspc config auto_cancel true
bspc config initial_polarity second_child
bspc config ignore_ewmh_focus true # prevent stealing focus
#bspc config bottom_padding 30

# set up workspaces/desktops
bspc monitor -d 1 2 3 4 5 6 7 8 9 0

# rules
bspc rule -a Yad state=floating layer=above
bspc rule -a Steam state=floating focus=off
bspc rule -a mpv state=floating
bspc rule -a discord desktop=^4
bspc rule -a qBittorrent state=floating desktop=^5
bspc rule -a Pavucontrol state=floating
bspc rule -a Org.gnome.Nautilus state=floating
bspc rule -a "Microsoft Teams - Preview" desktop=^3

steamlib=~/.local/share/Steam    # path to your steamlibrary
mygames="$(ls $steamlib/steamapps/appmanifest_*.acf | sed 's/[^0-9]*//g')"    # this sed command removes everything but the digits

for game in $mygames; do
    bspc rule -a steam_app_$game state=fullscreen layer=above
done

# scratchpad
bspc rule -a "Alacritty:scratchpad" sticky=on state=floating hidden=on
~/.config/bspwm/start_scratch.sh
