#! /bin/sh

# background
feh --bg-fill .config/bspwm/wallpaper.jpg & # wallpaper
pgrep -x sxhkd > /dev/null || sxhkd & # hotkey daemon
pgrep -x polybar > /dev/null || polybar bottom & # bottom status bar
pgrep -x picom > /dev/null || picom --experimental-backends & # x composer
pgrep -x fcitx > /dev/null || fcitx & # imput method framework
pgrep -x dunst > /dev/null || dunst & # notifications

xsetroot -cursor_name left_pt # change cursor

# constants
bspc config top_padding        0
bspc config bottom_padding     0
bspc config left_padding       0
bspc config right_padding      0
bspc config border_width       4
bspc config window_gap         16

# monocle
#bspc config borderless_monocle true
#bspc config gapless_monocle true
bspc config single_monocle true

# border colors
bspc config urgent_border_color		"#d79921"
bspc config focused_border_color	"#928374"
bspc config active_border_color		"#504945"
bspc config normal_border_color		"#3c3836"

# opacity
bspc config normal_frame_opacity 1
bspc config focused_frame_opacity 1

# multihead behavior
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

# focusing behavior
bspc config focus_follows_pointer false
bspc config history_aware_focus true
bspc config focus_by_distance true

# misc
bspc config split_ratio 0.50
bscp confic automatic_scheme longest_side
bspc config auto_alternate true
bspc config auto_cancel true
bspc config initial_polarity second_child
bscp config center_pseudo_tiled false
bspc config ignore_ewmh_focus true # prevent stealing focus
#bspc config bottom_padding 30

# set up displays
bspc monitor -d 1 2 3 4 5

# rules
bspc rule -a Yad state=floating layer=above
bspc rule -a Steam state=floating focus=off

steamlib = ~/.local/share/Steam    # path to your steamlibrary
mygames = $(ls $steamlib/steamapps/appmanifest_*.acf | sed 's/[^0-9]*//g')    # this sed command removes everything but the digits 

for game in $mygames; do
    bspc rule -a steam_app_$game state=fullscreen layer=above
done
