UP add volume +5
DOWN add volume -5

z add sub-delay -0.1
x add sub-delay 0.1
c set sub-delay 0

Z add audio-delay -0.1
X add audio-delay 0.1
C set audio-delay 0

# unbind s for screenshot
s ignore

ENTER cycle pause
